"""Add leave entilement"

Revision ID: e860c4a8f7e7
Revises: b975de27029f
Create Date: 2024-08-21 17:26:15.614004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e860c4a8f7e7'
down_revision = 'b975de27029f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('leave_entitlement', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'leave_entitlement')
    # ### end Alembic commands ###
